### ISSUE TITLE
white background issue

### ISSUE THREAD

**Issue by Fanyu7** [branu-ws/v-drag#4]
It shows white background when dragging or clicking the modal.
![white-background-issue](https://user-images.githubusercontent.com/34223140/37381345-f419b330-277f-11e8-9112-ba60072ab4dd.gif)

**Comment by lmiller1990** [comment]
Fixed this by making modal absolute position https://github.com/branu-ws/v-drag/commit/6e3d1266810c1b33e03719a91a464774acfae323
