### ISSUE TITLE
v-dragを使って、クリックイベントある時にz-indexの調整が必要

### ISSUE THREAD

**Issue by Fanyu7** [branu-ws/v-drag#7]
## 問題点

v-dragに、下記のようなz-index:1000のoverlayのdivを作っている。
そのため、v-dragを使って、クリックイベントがある時に、このoverlayよりも上に重ならないと、イベントは検知されない。

```
const overlay = document.createElement('div')
  overlay.setAttribute('style', `
    width: 100vw; 
    height: 100vh; 
    position: absolute;
    top: 0;
    left: 0;
    z-index: 10000;
  `)
```

## 解決案

- 暫定的な解決案は、v-dragを使う時、z-indexを1000以上に指定する
```
<div v-drag style="z-index:10001; position:absolute">
```

- 将来的には、v-dargを修正し、クリックイベントがある時に自動的にz-indexを10001にする。

**Comment by lmiller1990** [comment]
ベストは、`v-drag`がある要素に`z-index: 10001`を自動につけたらいいと思います。

@yk-hirao やる興味がありますか？

以上の説明にわからないことがあれば聞いてみて。

**Comment by lmiller1990** [comment]
Easy one, fixed in  https://github.com/branu-ws/v-drag/commit/14192912e4978aa3a6949bd56bb09d25959522c1

Install latest version:

`npm install @branu-jp/v-drag@next`

**Comment by lmiller1990** [comment]
Would be nice to have a test for

```
function adjustElementZIndex(el, index) {
  el.style.zIndex = index;
}
```

will make issue!
