### ISSUE TITLE
Add test for adjustElementIndex

### ISSUE THREAD

**Issue by lmiller1990** [branu-ws/v-drag#8]
Would be nice to have a test for

```
function adjustElementZIndex(el, index) {
  el.style.zIndex = index;
}
```

which is in `src/index.js`.  This function currently does not have a test.

Good first issue.

@yk-hirao or @Fanyu7 maybe you can add it

**Comment by yk-hirao** [comment]
you added commit it !! 👍 
commit `14192912`
